site_name: Distributed Scraping Network Leaf

theme:
  name: "material"

plugins:
- mkdocstrings:
    default_handler: python

nav:
  - Organization Home: https://spatiotemporal-wildlife-classification.github.io/
  - Home: index.md
  - How to use: use.md
  - Leaf Documentation: code.md